# based on image ci-o3de-extras:latest run compilation every PR and daily on main

name: o3de-extras-compilation-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  compilation_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Run Compilation
        uses: docker://ci-o3de-extras:latest
        with:
          args: |
            sh -c "echo 'Running compilation'"

      # Rest of your workflow steps...